name: Terraform Deployment

on:
  workflow_call:

permissions:
  id-token: write
  contents: read


jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    outputs:
      plan-status: ${{ steps.terraform-plan.outcome }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.5

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::304707804854:role/GitHubActionsOIDCRole
            aws-region: us-east-1

      - name: Debug AWS credentials
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: terraform-plan
        run: terraform plan -out=tfplan.out

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan.out

  wait-for-approval:
    name: ⏸️ Wait for Manual Approval
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment:
        name: pro
    steps:
      - name: Approval gate
        run: echo "Waiting for manual approval..."

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: wait-for-approval
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.5

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::304707804854:role/GitHubActionsOIDCRole
            aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: terraform-plan
        run: terraform plan -out=tfplan.out

      - name: Terraform Apply
        run: terraform apply tfplan.out
